
[package]
name = "stm32f407-rust-blink"
version = "0.0.1"
edition = "2024"

[dependencies]
cortex-m = "0.6"
cortex-m-rt = "0.6"
stm32f4xx-hal = { version = "0.10.0", features = ["stm32f407"] }
panic-halt = "0.2"  # A simple panic handler
#embedded-hal = "0.2"
